### ISSUE TITLE
Possible to exclude output cells?

### ISSUE THREAD

**Issue by reckoner** [kracekumar/jut#12]
I don't see a command-line flag for this? Is there a way to do this?

**Comment by kracekumar** [comment]
As of now, there is no way to ignore rendering the output cells. Do you mean an option `--ignore-output-cell` which will prevent displaying the relevant output of the cells so the user will have a look only at the input cells?

**Comment by reckoner** [comment]
Yes. that's exactly what I mean! This is a great tool and this would be a great enhancement.

**Comment by kracekumar** [comment]
It's fixed in https://github.com/kracekumar/jut/commit/5bb85b41039a690e5974397e8c879d19b57fb464. You can update jut `pip install -U jut==0.0.20` and use the feature. 

Feel free to file any reports. Thanks.
