### ISSUE TITLE
Strip vertical bars from displayed output

### ISSUE THREAD

**Issue by reckoner** [kracekumar/jut#13]
Selecting and copying blocks within the reported output includes the `|` symbol, which makes it tedious to strip out these symbols to get the valid embedded Python code. The visual display is great, but sometimes it makes working with the output in the terminal tedious.

**Comment by kracekumar** [comment]
Can you share a screenshot to demonstrate so that we both are on the same page?

**Comment by reckoner** [comment]
![image](https://user-images.githubusercontent.com/173637/116595601-578a0f00-a8d8-11eb-942f-96249d697243.png)

**Comment by reckoner** [comment]
That would be excellent!

**Comment by kracekumar** [comment]
This is fixed in latest main branch, can you check and let me know if solves your case?

**Comment by reckoner** [comment]
Brilliant! It works great and is *so* easy now to copy/select code out of the terminal!

**Comment by kracekumar** [comment]
Thanks for the feedback.
