### ISSUE TITLE
RFE: simplify cli by accepting a non-option path/url

### ISSUE THREAD

**Issue by ankostis** [kracekumar/jut#8]
(great thanks for your nice tool!)

It would be a handy enhancement for the CLI to accept a positional argument and guess whether it's a URL or FILE, an ac accordingly.

**Comment by kracekumar** [comment]
thanks for the suggestion.

If I understand it properly, the suggested CLI command will look like `$jut notebook.ipynb --start 1 --end 10` and `$jut raw.github.com/some/url.ipynb --start 1 --end 10` @ankostis?

**Comment by ankostis** [comment]
Exactly!

**Comment by kracekumar** [comment]
This is now in master after the commit https://github.com/kracekumar/jut/commit/aaeb163752c27d90437fc9b5ed74a5bdd8d9dee4, `pip install -U jut` should work. 

thanks!
